// <auto-generated />
using System;
using Embique.DocumentManagementApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Embique.DocumentManagementApi.Migrations
{
    [DbContext(typeof(DocumentAppDbContext))]
    partial class DocumentAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Embique.DocumentManagementApi.Models.DocumentModel", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FileType")
                        .HasColumnType("integer");

                    b.Property<string>("FileUploadedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FileId");

                    b.ToTable("documentModels");

                    b.HasData(
                        new
                        {
                            FileId = new Guid("9c1f5f7b-bf53-4f75-85e3-d9a1d5e4e2a1"),
                            Author = "ABC",
                            DateOfCreation = new DateTime(2024, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            FilePath = "/uploads/sample1.pdf",
                            FileType = 0,
                            FileUploadedBy = "User1",
                            Metadata = "Data1",
                            Title = "Sample Document 1"
                        },
                        new
                        {
                            FileId = new Guid("5bfe2e5e-d8b7-4786-b2e9-22fd8fdcc022"),
                            Author = "DEF",
                            DateOfCreation = new DateTime(2024, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            FilePath = "/uploads/sample2.docx",
                            FileType = 1,
                            FileUploadedBy = "User2",
                            Metadata = "Data1",
                            Title = "Sample Document 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
